ARG ASSET_BUCKET_URL

# ==========================================
# Stage 1: Build Frontend
# ==========================================
# We use a Python base image so we can easily install 'nf_robot' 
# and give 'sync_protos.py' access to the installed protos.
# We then install Node.js to handle the frontend build.
FROM python:3.11 AS build-stage

ARG ASSET_BUCKET_URL
ENV VITE_ASSET_BUCKET_URL=$ASSET_BUCKET_URL

WORKDIR /app

# Install Node.js 20 for frontend build
RUN apt-get update && apt-get install -y ca-certificates curl gnupg && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && apt-get install -y nodejs build-essential

# Install latest nf_robot for the proto files
# This ensures sync_protos.py can find 'nf_robot' in the site-packages
RUN pip install --no-cache-dir nf_robot==3.4.3

# Setup Frontend Directory
WORKDIR /app/nf-viz

# Copy frontend source (including package.json and sync_protos.py)
COPY ./nf-viz .

# Build Frontend
# This runs "npm run proto" -> "python3 sync_protos.py" -> extracts protos -> "pbjs" -> build
RUN npm install
RUN npm run build


# ==========================================
# Stage 2: Final Runtime Image
# ==========================================
FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install Python Dependencies
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy Backend Code
COPY app ./app

# Copy Built Frontend Assets from Stage 1
# We copy the 'dist' folder generated by vite to the location the backend expects
COPY --from=build-stage /app/nf-viz/dist ./nf-viz/dist

# Expose the port
EXPOSE 8080

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "1"]