import os
import logging
from typing import Optional
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker, DeclarativeBase, Mapped, mapped_column
from sqlalchemy import String, select, UniqueConstraint

# Format: postgresql+asyncpg://user:password@host:port/dbname
DATABASE_URL = os.getenv("DATABASE_URL", "")
logger = logging.getLogger(__name__)

engine = create_async_engine(
    DATABASE_URL,
    # 'pool_pre_ping' verifies the connection is alive before handing it to the app.
    pool_pre_ping=True,
    # 'pool_recycle' closes and recreates connections after they reach a certain age (seconds).
    pool_recycle=1800,
    pool_size=5,
    max_overflow=10
)

async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

class Base(DeclarativeBase):
    pass

class RobotOwnership(Base):
    __tablename__ = "robot_ownership"
    
    # user_id is the Firebase UID
    user_id: Mapped[str] = mapped_column(String, primary_key=True)
    # robot_id is the ID generated by observer.py when a configuration file is created.
    robot_id: Mapped[str] = mapped_column(String, primary_key=True, index=True)
    # The nickname provided by the user during the binding process
    nickname: Mapped[Optional[str]] = mapped_column(String, nullable=True)

class RobotSharedAccess(Base):
    __tablename__ = "robot_shared_access"
    
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    # The robot being shared
    robot_id: Mapped[str] = mapped_column(String, index=True)
    # The Firebase UID of the owner who granted this access
    owner_id: Mapped[str] = mapped_column(String)
    # The email of the person granted access. Normalized to lowercase.
    guest_email: Mapped[str] = mapped_column(String, index=True)
    
    # Prevent duplicate sharing of the same robot to the same email
    __table_args__ = (
        UniqueConstraint('robot_id', 'guest_email', name='_robot_guest_uc'),
    )

class UserExternalTokens(Base):
    __tablename__ = "user_external_tokens"
    
    # The Firebase UID
    user_id: Mapped[str] = mapped_column(String, primary_key=True)
    
    # Hugging Face Data
    hf_access_token: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    hf_username: Mapped[Optional[str]] = mapped_column(String, nullable=True)

async def init_db():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

async def get_db():
    async with async_session() as session:
        yield session