import os
import logging
from typing import Optional
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker, DeclarativeBase, Mapped, mapped_column
from datetime import date, datetime, timedelta, timezone
from sqlalchemy import String, Float, Date, DateTime, func, select, UniqueConstraint
from sqlalchemy.dialects.postgresql import insert as pg_insert

# Format: postgresql+asyncpg://user:password@host:port/dbname
DATABASE_URL = os.getenv("DATABASE_URL", "")
logger = logging.getLogger(__name__)

engine = create_async_engine(
    DATABASE_URL,
    # 'pool_pre_ping' verifies the connection is alive before handing it to the app.
    pool_pre_ping=True,
    # 'pool_recycle' closes and recreates connections after they reach a certain age (seconds).
    pool_recycle=1800,
    pool_size=5,
    max_overflow=10
)

async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

class Base(DeclarativeBase):
    pass

# --- User roles ---
# A user (identified by Firebase UID) may hold more than one role, so roles are
# stored one-per-row rather than as a single column on a user record.
ROLE_ROBOT_OWNER = "robot_owner"
ROLE_EMPLOYEE_BASIC = "employee_basic"
ROLE_EMPLOYEE_ADMIN = "employee_admin"

# Every role the application recognizes; used to reject typos when assigning roles.
VALID_ROLES = frozenset({ROLE_ROBOT_OWNER, ROLE_EMPLOYEE_BASIC, ROLE_EMPLOYEE_ADMIN})

# Roles that count as "an employee" for pages/endpoints gated to staff.
EMPLOYEE_ROLES = frozenset({ROLE_EMPLOYEE_BASIC, ROLE_EMPLOYEE_ADMIN})

class UserRole(Base):
    __tablename__ = "user_roles"

    # user_id is the Firebase UID. (user_id, role) is the primary key so a user
    # can hold several roles but never the same role twice.
    user_id: Mapped[str] = mapped_column(String, primary_key=True)
    role: Mapped[str] = mapped_column(String, primary_key=True)

class RobotOwnership(Base):
    __tablename__ = "robot_ownership"
    
    # user_id is the Firebase UID
    user_id: Mapped[str] = mapped_column(String, primary_key=True)
    # robot_id is the ID generated by observer.py when a configuration file is created.
    robot_id: Mapped[str] = mapped_column(String, primary_key=True, index=True)
    # The nickname provided by the user during the binding process
    nickname: Mapped[Optional[str]] = mapped_column(String, nullable=True)

class RobotSharedAccess(Base):
    __tablename__ = "robot_shared_access"
    
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    # The robot being shared
    robot_id: Mapped[str] = mapped_column(String, index=True)
    # The Firebase UID of the owner who granted this access
    owner_id: Mapped[str] = mapped_column(String)
    # The email of the person granted access. Normalized to lowercase.
    guest_email: Mapped[str] = mapped_column(String, index=True)
    
    # Prevent duplicate sharing of the same robot to the same email
    __table_args__ = (
        UniqueConstraint('robot_id', 'guest_email', name='_robot_guest_uc'),
    )

class UserExternalTokens(Base):
    __tablename__ = "user_external_tokens"
    
    # The Firebase UID
    user_id: Mapped[str] = mapped_column(String, primary_key=True)
    
    # Hugging Face Data
    hf_access_token: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    hf_username: Mapped[Optional[str]] = mapped_column(String, nullable=True)

class MetricMeasurement(Base):
    __tablename__ = "metric_measurements"

    # Long format: one row per (metric, day). Metric keys are defined in
    # app/metrics.py. Each distinct day is kept as history so the scoreboard can
    # plot scores over time, but a given metric may have only one score per day —
    # re-entering it for the same day overwrites that day's value (see the unique
    # constraint below).
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    # The day this measurement was taken.
    measured_on: Mapped[date] = mapped_column(Date, index=True)
    # One of metrics.METRIC_KEYS.
    metric_key: Mapped[str] = mapped_column(String)
    # The recorded score. Stored as float; integer-valued metrics round-trip fine.
    value: Mapped[float] = mapped_column(Float)
    # Firebase UID of the employee who entered it (for provenance).
    recorded_by: Mapped[Optional[str]] = mapped_column(String, nullable=True)

    # At most one score per metric per day.
    __table_args__ = (
        UniqueConstraint('measured_on', 'metric_key', name='_measurement_metric_uc'),
    )

class RobotActivity(Base):
    __tablename__ = "robot_activity"

    # One row per robot, tracking when it was last seen online. Used to count how
    # many distinct robots have been active recently (the "deployed" fleet size).
    robot_id: Mapped[str] = mapped_column(String, primary_key=True)
    last_seen: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True)


async def record_robot_seen(robot_id: str) -> None:
    """Upserts a robot's last-seen timestamp to now. Call when a robot connects."""
    now = datetime.now(timezone.utc)
    async with async_session() as session:
        await session.execute(
            pg_insert(RobotActivity)
            .values(robot_id=robot_id, last_seen=now)
            .on_conflict_do_update(index_elements=["robot_id"], set_={"last_seen": now})
        )
        await session.commit()


async def count_recently_active_robots(months: int = 3) -> int:
    """Number of distinct robots seen online within the last `months` (~30d each)."""
    cutoff = datetime.now(timezone.utc) - timedelta(days=months * 30)
    async with async_session() as session:
        result = await session.execute(
            select(func.count())
            .select_from(RobotActivity)
            .where(RobotActivity.last_seen >= cutoff)
        )
        return result.scalar_one() or 0


async def init_db():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

async def get_db():
    async with async_session() as session:
        yield session