import os
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker, DeclarativeBase, Mapped, mapped_column
from sqlalchemy import String, select

# Format: postgresql+asyncpg://user:password@host:port/dbname
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql+asyncpg://prod_user:password@localhost:5432/neufangled_prod")

engine = create_async_engine(DATABASE_URL)
async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

class Base(DeclarativeBase):
    pass

class RobotOwnership(Base):
    __tablename__ = "robot_ownership"
    
    # user_id is the Firebase UID
    user_id: Mapped[str] = mapped_column(String, primary_key=True)
    # robot_id is the ID generated by observer.py when a configuration file is created.
    robot_id: Mapped[str] = mapped_column(String, primary_key=True, index=True)
    # The nickname provided by the user during the binding process
    nickname: Mapped[Optional[str]] = mapped_column(String, nullable=True)

async def init_db():
    async with engine.begin() as conn:
        # Create tables if they don't exist
        await conn.run_sync(Base.metadata.create_all)

async def get_db():
    async with async_session() as session:
        yield session